### PR TITLE
Add use codeception

### PR DESCRIPTION
**Pull request by poohnix**
Streamlined and isolated version of PR #85 which should be way easier to comprehend, sorry for the previous detour!

### CODE REVIEW

**Comment by poohnix** [comment]
This PR adds a new option to specify that you want to use Codeception instead of PHPUnit. With the option "useCodeception" (which is false by default) the syntax is changed accordingly so that you are able to use Codeception (provided that you specified it's binary in the option "better-phpunit.phpunitBinary".

**Comment by calebporzio** [comment]
Hey @poohnix, sry for dragging my feat on this. My only last hesitation with this feature is it requires two config options to set up. 

Is it possible to do something like: if the user has set useCodeception config AND hasn't specified phpUnitBinary, then assume `codecept` binary.

What do you think? I'm just thinking it would lower the barrier to entry for CodeCeption users

**Comment by poohnix** [comment]
Hey @calebporzio, thanks for getting back to me on this. That is a brilliant idea I don't know why I have not done it in the first place. I have now changed the code (and tests) accordingly which even looks a bit cleaner to my eyes.

What do you think about these changes? I tried to do them in a way that is expandable if any similar options arise and need to be incorporated as well.

**Comment by poohnix** [comment]
Hey @calebporzio, I just noticed that you updated the code to include the IMHO very useful "run file" command. I have now integrated those changes in this PR as well, for easier merging (also it was just a straight forward "git merge master").

Have you since had the time to review this PR?

**Comment by poohnix** [comment]
Hi @calebporzio, I hope you are not already filtering my comments. ;-)

I have changed this PR to include the latest code changes by rewriting them according to the already changed functions in this PR. I think it is even a bit more streamlined this way. Would be great if you would consider including this PR.

Cheers, Hank

**Comment by calebporzio** [comment]
Hey @poohnix lol, no I haven't. Sorry I haven't gotten to this.

Anytime I expand the functionality, I increase the surface area for maintenance. I'd feel better about this if it had it's own dedicated command, like remote-command does.

How do you feel about that? I'd rather not, muddy up the main php-command file with codeception concerns. What do you think?

**Pull request closed without merging**
