### PR TITLE
Handles Pest filters

### PR DESCRIPTION
**Pull request by joedixon**

### CODE REVIEW

**Comment by amadeann** [comment]
@joedixon 
I don't have pest installed, and when I try to run tests tests I get the following error:
c:/laragon/www/m_project_name/vendor/bin/pest.bat : The term 'c:/laragon/www/m_project_name/vendor/bin/pest.bat' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I am on Windows 11.

**Comment by amadeann** [comment]
When I remove `pestphp/pest-plugin": true` line from `composer.json` and reopen VS Code tests run again. Since `    pestphp/pest-plugin": true` is a part of Laravel's default install, this will trip everybody up unless they use pest too. Maybe there is another way to detect if pest is in use?

**Comment by joedixon** [comment]
Hey @amadeann can you double check your composer.json?

The Pest binary will only be used if `pestphp/pest` is present.

**Comment by amadeann** [comment]
@joedixon 
Yes, I have checked it. I had `"pestphp/pest-plugin": true` in `config.allow-plugins`, which is a part of laravel/laravel default composer.json ([this line](https://github.com/laravel/laravel/blob/25070a3ffb175c15b59cd7f12289a9648165bba3/composer.json#L60)).

**Comment by joedixon** [comment]
@amadeann good catch. I'll submit a PR to make this check a little more explicit.

**Comment by joedixon** [comment]
@amadeann think this should do it: https://github.com/calebporzio/better-phpunit/pull/138

**Comment by amadeann** [comment]
Works as before with the new version :)

**Comment by joedixon** [comment]
@amadeann to confirm, you mean before you ran into the issue? i.e. it's working as expected?

**Comment by amadeann** [comment]
@joedixon 
Yes, works as expected with your fix from yesterday. Sorry it wasn't clear from my message.

**Pull request merged**
