### PR TITLE
Adds XML configuration filepath option

### PR DESCRIPTION
**Pull request by fuel-odrais**
Sometimes you want to run a suite of tests using a specific XML configuration file.

This setting allows the user to set the configuration file absolute path to use for all tests.

### CODE REVIEW

**Comment by calebporzio** [comment]
Sorry for the wait - thanks for the PR

**Comment by marcelloh** [comment]
So I have this:
```
"better-phpunit.xmlConfigFilepath": ".tests/phpunit_all.xml",
```
and I now see this:
```
> Executing task in folder AllUnited_Smart: ./vendor/phpunit/phpunit/phpunit c:/Data/git/AllUnited_Smart/tests/Initial/InitialTest.php --filter '^.*::testInitializer( with data set .*)?$' --configuration .tests/phpunit_all.xml <


Terminal will be reused by tasks, press any key to close it.
```
which opens a popup from win dows asking me how I want to open the file????

**Comment by marcelloh** [comment]
Changed it to ./tests without any difference.
Tried command line, same result.
changed command line to full xml location, same result.

strange that the path has to be absolute since the first command is a relative path too.....
If that is a fact, it should be in the manual (and the configuration should be checked for it as well)

**Comment by ostindrais** [comment]
You're on Windows, right? I forget often that Windows uses backslashes
("\") instead of forward-slashes ("/") to separate folder names.
Have you tried changing the forward-slashes in the paths to backslashes?

**Comment by marcelloh** [comment]
Windows can use both separators these days, but for the sake of the argument, let me try this.

So I took the commandline, changed all forward to backward slashes: no result.
I wrote the full location name with backward slashes again: no result

**Comment by marcelloh** [comment]
I changed the configuration not to use the phpunit, but to use a batch file, which I normally use to have my tests fired. It now can be used to fire just one testfile, and better-phpunit now can run a testfile via that bactchfile. That's enough for me right now. So the issue can be closed.

**Pull request merged**
