### PR TITLE
[WIP] Rerun failed test

### PR DESCRIPTION
**Pull request by thecrypticace**
This is a definite WIP but it should be good enough to test and initiate a discussion around.

This is an example that provides a command to reruns failed tests.

VSCode definitely has some oddities around running tasks. Another issue is, because the way PHPUnit is being run (via a task), it doesn't make it easy to run multiple consecutively afaict (though I may be missing something here). As PHPUnit doesn't offer a simple way in one command to run a subset of tests from file A, a subset from file B, etc… I've opted to use the filters for this but some things have fallen out because of that:

Tests are not currently limited to a given file. I'm working on fixing this. Another thing is that much of this could use a larger refactoring to simplify things and make it simpler to deal w/ the global state that is being used.

We could probably get around some of the issues by writing out a temporary configuration file w/ suites but that seems like a rather significant amount of work.

### CODE REVIEW

**Comment by calebporzio** [comment]
image

**Comment by calebporzio** [comment]
Thanks for the PR - it didn't work for me out of the gate because of that dependency issue. 

Good approach though - this feature would be super dope

**Comment by thecrypticace** [comment]
I forgot to update the lock file. Whoops. Try it now?

**Comment by calebporzio** [comment]
Closing this for now - thanks

**Pull request closed without merging**
