### PR TITLE
Add additonal suite options

### PR DESCRIPTION
**Pull request by poohnix**
Streamlined version of PR #84 which should be way easier to comprehend, sorry for the previous detour!

### CODE REVIEW

**Comment by poohnix** [comment]
This PR let's you add an option to only the 'run suite' command. This is useful if you want to specify '--testsuite unit' (my previous use case in PR #84) but it also let's you specify things like '--coverage' that really only make sense to be run against the whole suite and not on single files or even methods (like commandSuffix would).

**Comment by calebporzio** [comment]
Awesome @poohnix! Sorry for leaving you hanging on this, this is a great addition. This is a really clever solution and I will definitely be using it myself!

**Comment by calebporzio** [comment]
I AM going to change the name from `suiteOptions` to `suiteSuffix` to stick with convention. Does this make sense to you?

**Comment by poohnix** [comment]
@calebporzio Changing the name of the option to `suiteSuffix` totally makes sense as it is way more in line with the other options. Good catch and thanks for adding it!

**Pull request merged**
