### PR TITLE
Generate HTML or text coverage

### PR DESCRIPTION
**Pull request by walkero-gr**
Hello there,
I added the feature to have PHPUnit generated from the extension, both for simple run and suite run. 
Have in mind that my code is based on the version 1.2.2, and not the latest, but the sections that I changed should not be a big trouble to be merged.

Hope you like it and will be useful to the users.

### CODE REVIEW

**Comment by calebporzio** [comment]
Interesting - I'm open to this addition. Thoughts:

* nicely done PR, code's pretty clean
* you left a TODO in there
* I'm hesitant to add so many additional commands, is there one command that would fit most use cases? Like, I'm thinking maybe we just add a coverage command for the entire suite and make it the most common default (I don't actually know weather that's text or html, but one of those). What do you think? do you mind pairing this down to one simple command?

Thanks for the PR!

**Comment by calebporzio** [comment]
Also, you'll need to rebase on the master branch, there is a new "suiteSuffix" config option that you'll need to account for in your "lastOutput" line

**Comment by walkero-gr** [comment]
@calebporzio Glad you liked the PR

> you left a TODO in there
Basically is a TODO about showing an error message to the user if he forgot to set the "Coverage File Path", but to be honest, I am not sure yet how to do it. It doesn't block the usage of the coverage feature

> do you mind pairing this down to one simple command
I totally don't mind. The thing is that the HTML is more complete against the text information, but it takes a lot more time to generate. That's why I set 4 different coverage commands. I thought to so a default configuration variable, but the user should go and change it all the time. This would minimise it to two commands. I'd like to hear your opinion on that.

> Also, you'll need to rebase on the master branch
I have some issues to have the latest version to work on my system, since the VSCode is stuck in v.1.30. I will try to find a solution and make a new PR with the latest version.

**Comment by calebporzio** [comment]
Great, yeah see if you can upgrade your VS Code version.

Also, It might be best to have a "codeCoverage" command with config option for text/html like you said - that makes the most sense to me.

**Comment by walkero-gr** [comment]
This PR is for older version of Better-PHPUnit. A new one for the latest version is at https://github.com/calebporzio/better-phpunit/pull/95

**Pull request closed without merging**
