### PR TITLE
Adjust filter regexp

### PR DESCRIPTION
**Pull request by emil-nasso**
Adjusting filter regexp that is used when executing isolated tests to support tests with datasets.

### CODE REVIEW

**Comment by calebporzio** [comment]
last time I merged something like this it broke the extension for some people and I had to revert it.

I'm hesitant to pull this in until someone who's machine was broken by the old dataset regex addition says this works on it.

Thanks for the contribution though - maybe this one will be more resilient

**Comment by Nizari** [comment]
Is it possible to look at this issue though? You now can't use any dataproviders in practice because they won't run

**Comment by jdavidbakr** [comment]
I've applied this patch to my local copy without any issue.

**Comment by calebporzio** [comment]
Ok, sounds good - let's keep an eye out for issues. Thanks for the contribution @emil-nasso !

**Comment by calebporzio** [comment]
Ok, new version: 1.2 has this feature in it

**Comment by antoniopaisfernandes** [comment]
Hi all,

It broke running tests on Windows :)

On Linux, it works fine.

Perhaps you could maintain the ( .*)? but if not running on Windows.

Best,
António

**Comment by calebporzio** [comment]
Ok, just published 1.2.2 - see if it's fixed for you on windows @antoniopaisfernandes and let me know please!

**Comment by calebporzio** [comment]
Sweet!

**Pull request merged**
